### ISSUE TITLE
`AgBehenate` visualization -- find right vmax for powder display

### ISSUE THREAD

**Issue by apeck12** [lcls-users/btx#103]
Look into whether there's a better `vmax` setting for the powder subplot produced by `AgBehenate`, since sometimes the region at low q is saturated.

**Comment by carbonscott** [comment]
@apeck12 I wonder if saturation issue will be mitigated by visualizing an image after z-score normalization.  Then, `vmin = 0 or -1` and `vmax = 1`.  `1` is supposed to be the std of the image.  Of course, the histogram of pixels won't follow a Gaussian distribution, so how much better it will look like won't be guaranteed (but hopefully still better).
