### ISSUE TITLE
Rayonix detector distance estimate is wrong by roughly 200%

### ISSUE THREAD

**Issue by fredericpoitevin** [lcls-users/btx#110]
For mfxlx5520, the distance estimated was ~58.4mm for runs 2 and 3.
Measuring with a tape, it looks like we might be closer to 80mm - which should roughly give 1.7A at the edge.

**Comment by apeck12** [comment]
Interesting. Looking at the fits, it seems that the distance inferred is 75.9 mm during the first iteration (prior to any centering) is 75.9 mm. Maybe a matter of changing the dq range? I'll take another look.

**Comment by apeck12** [comment]
Improved `vmax` for visualization, with `delta_qs = np.arange(0.01,0.05,0.00005)`. Estimated detector distance of 58.33 mm.
![download-2](https://user-images.githubusercontent.com/6363287/168353728-d2995e86-70dd-46bd-9eb9-fe7a3c4e9942.png)

**Comment by carbonscott** [comment]
@apeck12 @fredericpoitevin Is there any reason to choose average over max?  During the beamtime two weeks ago, Chuck suggested that I should do centering using large circles whenever possible.  Max image will do a better job revealing large circles.

**Comment by fredericpoitevin** [comment]
@carbonscott the powder used here is the max.

**Comment by fredericpoitevin** [comment]
What would be interesting to figure out is the discrepancy between the distance inferred from this plot (or from looking at rings in a GUI like psocake) and the distance measured with a ruler in the beamline.

**Comment by fredericpoitevin** [comment]
The following series of AgBehenate runs was collected yesterday during `mfxlx5520`:

| run # | `clen` (mm)  | (est.) distance (mm) | (est.) edge res. (A) | (est.) center (pix) |
|------|--------|---------------|-----------------|-------------|
| 88 | 300 | 102.08 | 1.90 | (963.29, 959.22)
| 89 | 270 | 87.58 | 1.72 | (962.75, 960.12) |
| 90 | 250 | 77.05 | 1.60 | (962.85, 959.49) |
| 91 | 230 | 67.35 | 1.49 | (962.67, 958.78) |
| 92 | 210 | 56.98 | 1.37 | (963.12, 959.05) |

Visual investigation with `psocake` of run 84 seemed to corroborate that when `clen=210` then the distance should be `57mm` since the LCP ring then matches roughly 4.5A.

What does *not* make sense is that when measuring the distance with a ruler, we get a distance of roughly 115mm...

**Comment by carbonscott** [comment]
@fredericpoitevin Detector distance needs to be accurate so that indexing can find meaningful parameters (like they follow a Gaussian distribution).  Do you know which one leads to a better indexing result?  (57 mm or 115 mm). 

A side note, detector distance should be able to refine during indexing too, but it seems existing software doesn't support it.

**Comment by carbonscott** [comment]
I had mistaken the average for max because the title of the bottom panel shows "average ag behenate".  Now I recall it's also called average in psocake.  So let's maybe ignore it for now.

**Comment by fredericpoitevin** [comment]
> I had mistaken the average for max because the title of the bottom panel shows "average silver behenate". Now I recall it's also called average in psocake. So let's maybe ignore it for now.

yes it says "radially averaged".

**Comment by fredericpoitevin** [comment]
> @fredericpoitevin Detector distance needs to be accurate so that indexing can find meaningful parameters (like each of the parameters follows a Gaussian distribution). Do you know which one leads to a better indexing result? (57 mm or 115 mm).
> 
> A side note, detector distance should be able to refine during indexing too, but it seems existing software doesn't support it.

In theory what you say is correct, and we are aware of this. Turns out things are a bit more complicated - will report here once solved.

**Comment by fredericpoitevin** [comment]
Some progress was made - `psana` might not be reporting the actual binned pixel size for the Rayonix.

Consider run 92 where the Rayonix is binned 4x4 and run 93 where it is binned 6x6.

```python
import psana
ds = psana.DataSource('exp=mfxlx5520:run=92)

det = psana.Detector('Rayonix', ds.env())
psana_reported_pixel_size = det.pixel_size(ds.env)

env = ds.env()
cfg = env.configStore()
actual_pixel_size = cfg.get(psana.Rayonix.ConfigV2).pixelWidth())

print(f'Reported value: {psana_reported_pixel_size} vs Actual value: {actual_pixel_size})
```
>> Reported value: 89.0 vs Actual value: 176

```python
import psana
ds = psana.DataSource('exp=mfxlx5520:run=92)

det = psana.Detector('Rayonix', ds.env())
psana_reported_pixel_size = det.pixel_size(ds.env)

env = ds.env()
cfg = env.configStore()
actual_pixel_size = cfg.get(psana.Rayonix.ConfigV2).pixelWidth())

print(f'Reported value: {psana_reported_pixel_size} vs Actual value: {actual_pixel_size})
```
>> Reported value: 89.0 vs Actual value: 264

So for some reason, `psana` reports 89.0mm no matter what. It might be due to the fact that the following line has been commented out in the `Detector` code:

```python
    def pixel_size_rayonix(self):
        """Dan can't guarantee that pixel size in the rayonix_config_object is sufficiently precise.
        """
        c = pda.get_rayonix_config_object(self.env, self.source)
        if c is None: return None
        return c.pixelWidth()


    def pixel_size(self, par):
        #if self.dettype == gu.RAYONIX: return self.pixel_size_rayonix()
        if self.geoaccess(par) is None: return None
        else:
            if  self.pixel_size_val is None:
                self.pixel_size_val = self.geo.get_pixel_scale_size()
        return  self.pixel_size_val
```

**Comment by fredericpoitevin** [comment]
This fixed our detector distance estimate, which now reads 112.75mm for a `clen` of 210mm - which roughly matches what we measure with a ruler.

**Comment by apeck12** [comment]
Phew. Thanks for catching that, @fredericpoitevin! Now I'm actually pretty confused, since it looks like we were off by a factor of 2 for the pixel size in mfxp22820:
```
psi = PsanaInterface('mfxp22820', 57, 'Rayonix')
print(f"Image shape: {psi.get_images(1, assemble=False)[0].shape}")
print(f"Confused pixel size: {psi.get_pixel_size()} mm")
print(f"Actual pixel size: {get_true_pixel_size(psi)} mm")
```
returns:
```
Image shape: (1920, 1920)
Confused pixel size: 0.089 mm
Actual pixel size: 0.176 mm
```
So maybe we were in a regime of missing the true periodicity in the behenate spacing by a factor of 2 for that experiment, which in the end compensated for the fact that our pixel size was off by a factor of 2? I'll take a look...

**Comment by fredericpoitevin** [comment]
That was a nice brain noodling endeavour indeed!

The main thing to realize is that as long that the ratio of pixel size and detector distance is kept constant, nothing bad happens in the scaling of the reciprocal space.

So we get the right resolution and q-values with a pixel size that is off by a factor of 2, as long as the detector distance is off by the same factor.
