### ISSUE TITLE
Hit powder

### ISSUE THREAD

**Issue by fredericpoitevin** [lcls-users/btx#122]
It would be useful to produce a powder plot of the "hits" found by peak finder, once it is done.

**Comment by apeck12** [comment]
@fredericpoitevin, sorry -- I don't think I put two and two together when you mentioned this earlier. It's possible we already have this stored under `/entry_1/data_1/powderHits` in the cxi files: https://github.com/lcls-users/btx/blob/f28bdadbf86826f0a97846a8ba656ba23ec33258/btx/processing/peak_finder.py#L253.

This is reshaped to mimic CrystFEL conventions, which won't matter for the Rayonix. For other detectors, the reshaping can be accomplished by loading it as a CrystFEL-style mask in the `MaskInterface` class.

**Comment by apeck12** [comment]
@fredericpoitevin - on closer inspection, I think something like the following in the `summarize` function of `PeakFinder` should work to display the powder. It looks like we already import the functions in the if statement from psana_interface.py.
```
if self.psi.det_type != 'Rayonix':
    pixel_index_map = retrieve_pixel_index_map(self.psi.det.geometry(self.psi.run))
    powder_hits = assemble_image_stack_batch(self.powder_hits, pixel_index_map) 
else:
    powder_hits = self.powder_hits
plt.imshow(powder_hits)
plt.savefig(os.path.join(self.outdir, ‘powderhits.png’), dpi=300, bbox_inches=‘tight’)
```
