### ISSUE TITLE
Implement detector distance optimization task from crystal indexing.

### ISSUE THREAD

**Issue by fredericpoitevin** [lcls-users/btx#127]
At the moment we can estimate the detector distance and center based on AgBehenate powder. 

It might be relatively straightforward to do it from crystal data, by scanning `coffset` over a range and reporting the distance at which the indexing rate is maximal.

If we also scan over the detector center, then depending on `geoptimizer` (#89 ) becomes less of a problem.

Of course, for more complicated metrology optimization, we should sync-up with Mikhail, as @valmar pointed out.

**Comment by valmar** [comment]
So, on this topic, I added two links suggested by Alexandra.

One, the CrystFEL tutorial: https://gitlab.desy.de/thomas.white/crystfel/-/blob/master/doc/articles/tutorial.rst

She suggests reading from the part "Advanced: Check and optimise the detector geometry"

Second her thesis, section 5.1.2, that I attach

The bottom line seems to be: we should not maximize the indexing rate, but minimize the spread of the cell parameters

[5.1.3.pdf](https://github.com/lcls-users/btx/files/8703700/5.1.3.pdf)

The geoptimiser already optimizes the detector distance, using that is the path of least resistance (although learning how to use it might not be trivial)

**Comment by apeck12** [comment]
Thanks for the links and tip, @valmar!
