### ISSUE TITLE
Unit tests

### ISSUE THREAD

**Issue by apeck12** [lcls-users/btx#134]
We need to start thinking of unit / function tests. One item to check for several scripts is described below.

When we'll start testing, a good test will be to check the consistency between this argument list and what is expected by __init__(), etc.

_Originally posted by @fredericpoitevin in https://github.com/lcls-users/btx/pull/132#discussion_r877592768_

**Comment by fredericpoitevin** [comment]
Too big of an "issue" to deal in one pass, let's just try to add a few here and there!
