### ISSUE TITLE
CrystFEL and CCTBX dependencies

### ISSUE THREAD

**Issue by apeck12** [lcls-users/btx#135]
That was already true with `indexamajig` but the elephant in the room is the dependency on crystfel to 1) be available, 2) be the expected version (10.x here if I'm not mistaken).

Maybe we should make these dependencies explicit in the docstring?

Hopefully we manage to containerize things at some point so that this version of the code could be made to match a given version of an docker image, and updates in crystfel could be tracked in a more robust manner.

_Originally posted by @fredericpoitevin in https://github.com/lcls-users/btx/pull/132#discussion_r877587839_

**Comment by fredericpoitevin** [comment]
the JobScheduler kinda helps with this now.
