### ISSUE TITLE
Pull tag information from eLog

### ISSUE THREAD

**Issue by carbonscott** [lcls-users/btx#138]
To find the value of a particular run parameter for all runs: 
- Refer to [https://confluence.slac.stanford.edu/display/PCDS/API+access+to+the+LCLS2+eLog](https://confluence.slac.stanford.edu/display/PCDS/API+access+to+the+LCLS2+eLog)
- Prepare a minimal code that saves run numbers and tags into a `json` file.

**Comment by fredericpoitevin** [comment]
same as #79

**Comment by carbonscott** [comment]
@fredericpoitevin @irischang020 A nearly minimal example to find all runs associated with tag "DARK" from experiment `mfxlv4920`.  

- Get your authentication stuff right by running.
   ```
   kinit
   ```
- Run the following code from `psanagpu` nodes. 

  ```Python
  #!/usr/bin/env python

  import requests
  import json
  from krtc import KerberosTicket
  from pprint import pprint

  # Experiment to look into...
  exp = "mfxlv4920"

  # Biolerplate URL to fetch runs associated with tags...
  ws_url = f"https://pswww.slac.stanford.edu/ws-kerb/lgbk/lgbk/{exp}/ws/get_tags_to_runs"

  # Auth stuff...
  krbheaders = KerberosTicket("HTTP@pswww.slac.stanford.edu").getAuthHeaders()

  # Request...
  r = requests.get(ws_url, headers=krbheaders)

  # Obtain response...
  if r:
      tag_to_run_dict = r.json()['value']

      tag = "DARK"

      pprint(tag_to_run_dict[tag])
  ```

Let's maybe discuss where this feature should go in `btx`.

**Comment by fredericpoitevin** [comment]
Let's close this issue after the capability can be used within a DAG.

**Comment by carbonscott** [comment]
Sounds good.
