### ISSUE TITLE
Figure out how to trigger SPI reconstruction at NERSC

### ISSUE THREAD

**Issue by carbonscott** [lcls-users/btx#139]
Prerequisite for a reconstruction job:
- [x] `xtc2` files (I will prepare data from amo06516).
- [ ] A config file (maybe json or yaml) for `spinifel`.  In the config file, run numbers that are used for a single reconstruction job should be specified.

**Comment by carbonscott** [comment]
@irischang020 I've prepared a small-sized `.xtc2` file for testing.  You can find it here (`/reg/data/ana03/scratch/cwang31/xtc1to2/amo06516_r0090_single_hits.xtc2`) on `psanagpu` node.  I will follow it up with a large-sized `.xtc2` after I figure out the automated annotation (https://github.com/carbonscott/deepprojection/issues/2#issuecomment-1136230150).  Could you look into triggering SPI reconstruction at NERSC?  The below is a link to an existing approach to trigger a SLURM job via airflow. 

https://github.com/lcls-users/btx/blob/725121b4af27c193fae18fdf16a3b162598943d7/dags/plugins/jid.py#L23

It looks we might need a NERSC URL and a file path on their server.  

Let me know if there's an issue accessing the `.xtc2` file.

**Comment by fredericpoitevin** [comment]
@carbonscott at the moment we have only tested using `btx` DAGs through Airflow on the FFB nodes. If you intend to test launching jobs at NERSC, I suggest we schedule a meeting with Thorsten, Murali and Wilko first.

**Comment by carbonscott** [comment]
Thanks @fredericpoitevin for your suggestion.  Let's do that.

**Comment by irischang020** [comment]
@fredericpoitevin I would like to get involved. Please invite me to the meeting.

**Comment by irischang020** [comment]
- [ ]  transfer the .xtc2 file to NERSC and make sure we can access it with psana2
- [ ]  create a config file at NERSC and use it within spiniFEL, specifically the config file grows over time => need to make software design decisions
- [ ] preprocess (e.g., mask out bad pixels, denoise) the .xtc2 file

**Comment by fredericpoitevin** [comment]
Not critical
