### ISSUE TITLE
Reliable tool for detector distance estimation from the control room

### ISSUE THREAD

**Issue by fredericpoitevin** [lcls-users/btx#151]
# Needs
at any point during the beamtime, we should be able to get a good idea of the detector distance. The estimate should improve as beamtime progresses:
| step | action | expected precision |
|---|---|---|
| before beamtime | make sure the `calib/geometry/.dat` is latest | N/A | 
| before X-ray arrive | use a "traditional" offset  | center: ?<br>distance: +/- 1cm| 
| AgBehenate run | use space between rings  | center: few pixels <br>distance: +/- 1mm | 
| solution scattering run | use solvent ring | center: few pixels <br>distance: +/- 1mm | 
| crystal scattering set of runs | use indexing stats | center: sub-pixel <br>distance: sub-mm | 

# Approach
At any point, there will be a `scratch/btx/geom` directory containing the most up to date `.geom` file. 
Do we want to optionally update the `calib/geometry` directory with converted `.dat` files?

Importantly, this tool will be run from the control room by the beamline scientist and use the current PV value associated with the position of the detector unless a run number is given, in which case the PV value during that run will be used.

## Command-line 
Before X-ray arrive, we expect the following behavior:
```
mfx-daq:~> guestimate
  # mfxxxxx00 | run: 0 | detector: epix10k2M
  > distance = 100.3mm +/- infinity
  > res_max  = 2.1A    +/- infinity
  > res_min  = 20A     +/- infinity
```
A more verbose option:
```
mfx-daq:~> guestimate -v

  # guestimating distance for experiment: mfxxxxx00 | run: 0 | detector: epix10k2M 

  > Nominal distance retrieved from PV XX:YY:ZZ:01: 400.5mm

  # No geometry available, using our best guess for the offset...

  > Estimated distance between detector and IP is: 100.3mm +/- infinity
  > Resolution at the edge of the detector is: 2.1A +/- infinity
  > Resolution at the detector tube is: 20A +/- infinity

  # Done! 
```
Specifying the experiment, run and detector will make use of the latest available geometry generated by `btx`:
```
mfx-daq:~> guestimate -e mfxlx5520 -r 95 -d Rayonix -v 

  # guestimating distance for experiment: mfxlx5520 | run: 95 | detector: Rayonix
  
  > Nominal distance retrieved from PV AA:BB:CC:09: 213.5mm

  # Found geometry file: /cds/data/drpsrcf/mfx/mfxlx5520/scratch/btx/geom/r0085.geom`

  > Estimated distance between detector and IP is: 200.3mm +/- 1mm
  > Resolution at the edge of the detector is: 2.1A +/- ??
  > Resolution at the detector tube is: 20A +/- infinity

  # Done!
```
Specifying the type of the run will update the geometry using `btx`:
```
mfx-daq:~> guestimate -e mfxlx5520 -r 95 -d Rayonix -t agbehenate -v 

  # guestimating distance for experiment: mfxlx5520 | run: 95 | detector: Rayonix
  
  > Nominal distance retrieved from PV AA:BB:CC:09: 213.5mm

  # Creating geometry file: /cds/data/drpsrcf/mfx/mfxlx5520/scratch/btx/geom/r0095.geom`

  > Estimated distance between detector and IP is: 200.3mm +/- 1mm
  > Resolution at the edge of the detector is: 2.1A +/- ??
  > Resolution at the detector tube is: 20A +/- infinity

  # Done!
```

## Detector image display

In my opinion, the best approach is to build on OM, assuming the following requirements are met:
- it has been set up before beamtime and easily accessible by the beamline scientist during the beamtime (prepare windows)
- the `.geom` used by OM can be easily updated with the latest `btx` generated file.

**Comment by apeck12** [comment]
Revised approach:
- Create a new PV and store `coffset` in it. Each time geom_opt or geoptimizer is run, this PV will be updated with the new estimated `coffset`.
- Calling guestimate.py will then retrieve the `coffset` and `clen` from their respective PVs, add (or subtract) them to get the estimated detector distance, and report this value.
- guestimate.py will be called from the mfx-daq server, using something along the lines of `ssh -Y user@psana python guestimate.py`
- We may want to have both `--current` and `--run XX` options, in case a user wants to determine the PV from an earlier run before a change in the detector distance.

**Comment by fredericpoitevin** [comment]
Ultimately, we want this to be displayed in Grafana: https://pswww.slac.stanford.edu/ctl/grafana/dashboards/f/51ra50wMz/mfx

**Comment by fredericpoitevin** [comment]
This tool should be implemented in hutch-python.
