### ISSUE TITLE
Complete SFX analysis of runs 198-214.

### ISSUE THREAD

**Issue by fredericpoitevin** [lcls-users/btx#159]

**Comment by apeck12** [comment]
Unfortunately there aren't sufficient indexable crystals at low transmission to generate an mtz and assess quality with statistics like CC* and Rsplit. Peakograms can be found in Issue #160. Unit cell distributions looked similar across the range of transmissions used and are shown below:

**1% transmission**
![cell_sample1t](https://user-images.githubusercontent.com/6363287/182007843-71993072-720f-4b88-bdd1-6fcc3b638b87.png)

**5% transmission**
![cell_sample5t](https://user-images.githubusercontent.com/6363287/182007845-764c177a-6562-46b5-9fc0-e03d9915a1d1.png)

**9% transmission**
![cell_sample9t](https://user-images.githubusercontent.com/6363287/182007846-d419bbd0-a973-4f0c-8fc1-5897b1c4e5b5.png)

**10% transmission**
![cell_sample10t](https://user-images.githubusercontent.com/6363287/182007847-4b20eaae-d2b3-4acc-a5ac-5691b1345718.png)

**50% transmission**
![cell_sample50t](https://user-images.githubusercontent.com/6363287/182007848-8985e04e-becc-45e4-960d-6525f4165723.png)

**100% transmission**
![cell_sample100t](https://user-images.githubusercontent.com/6363287/182007850-f8d7b053-8d03-43b0-8df2-e80b5cebf0fb.png)

**Comment by fredericpoitevin** [comment]
https://docs.google.com/presentation/d/123UR6k9GYy0t7QWL-lhnCceGFVuQO3tZSRLqw577A_8/edit?usp=sharing
