### ISSUE TITLE
PiPCA: Maintain Projected Data in Updated PC Space

### ISSUE THREAD

**Issue by calhep** [lcls-users/btx#187]
Users would like the ability to visualize the projection of all captured image data onto the PC space of the most recent iPCA model. Presently these principal components lie in the projection space of the model **at the time they were retrieved**, and are not updated with future model updates. When the rate of convergence in the model is high, like at the start of a run, the PC's of subsequent batches might look as follows:

<img width="393" alt="image" src="https://user-images.githubusercontent.com/43707470/187592374-c7e1fa82-c841-47e9-8910-677ba28d1f39.png">

These data are misleading, so updating the PC's from past batches along with model updates is necessary. Research into how this update can be performed is needed.

**Comment by fredericpoitevin** [comment]
CLosed by #334
