### ISSUE TITLE
PiPCA: iPCA Launch Script with Parameter Tuning

### ISSUE THREAD

**Issue by calhep** [lcls-users/btx#189]
Currently all parameter selection is left to the discretion of the user, with only the most obvious safeguards in place. Since parameter initialization happens post-launch from within `ipca.py`, the size of the MPI world cannot be adjusted based on the number of stored components, or the dimension of the image data. This causes issues like those described in #188.

We would like to have an external script which selects the optimal size of the MPI world _r_ subject to other user-defined parameters like _d_, _q_, etc., and then launches _r_ copies of `ipca.py` in parallel.

**Comment by fredericpoitevin** [comment]
Let's leave this for later.
