### ISSUE TITLE
Detector geometry history

### ISSUE THREAD

**Issue by fredericpoitevin** [lcls-users/btx#2]
The current method for figuring out what was the latest geometry optimized for a given detector consists in consulting the following Confluence page: https://confluence.slac.stanford.edu/display/PSDM/Geometry+History#GeometryHistory-Geometries

It would be nice to have a centralized place to share optimized geometry files in a push/pull way, together with some documentation on how they were built and how others can deal with them.

**Comment by sbotha89** [comment]
Yes, agreed. Although when re-visiting old data people may want to start with a particular geometry file, so I do think a "catalog" based on experiment IDs and dates is a good initial ressource. If there's a repository here that gets pushed to a centralized location at LCLS that everyone can access, It shouldn't be hard to have a script that automatically points to the most recent one? Provided they are named consistently? What do you think?

**Comment by fredericpoitevin** [comment]
Thanks @sbotha89 this sounds great! Let me know if I can help setup something

**Comment by fredericpoitevin** [comment]
For geometry conversion, I'll add a little paragraph that gives the gist of https://confluence.slac.stanford.edu/display/PSDM/Geometry+converter+between+psan 

Ideally, a practical example with actual geometry files shared here would be nice for people to try. It took me a while to figure out `geometry_converted` only work in python 2 psana environments for example.

**Comment by fredericpoitevin** [comment]
Created #14 specifically for the format conversion issue.
