### ISSUE TITLE
cli options

### ISSUE THREAD

**Issue by yilaili** [lcls-users/btx#210]
Hi Fred,

As promised I have finally got the time to modify the code to add a cli option: https://github.com/yilaili/btx/tree/cli
Basically I wrote a wrapper `submit_main.py` around the `elog_submit.sh` to submit the job. `submit_main.py` has a number of flags which can be used to override the specs in the yaml file. It will create a new yaml file with a suffix `-tmp`.
Obviously I am not able to debug the script, so please let me know what you'd like me to to before I do a pull request. :)

**Comment by fredericpoitevin** [comment]
Hi Yilai, thanks so much! Very excited about this :D 

Submission goes great!
```bash
(myenv) [fpoitevi@drp-srcf-eb002 launchpad]$ submit_main.py -c ../yamls/t1calib25.yaml -t index -r 200 --index+tag clitest
Config edited according to the inputs.
elog_submit.sh --config ../yamls/t1calib25-tmp.yaml --task index --run_number 200
Submitted batch job 496185
Job sent to queue
```
However, there might be a little typo somewhere - here it the slurm output:
```bash
(myenv) [fpoitevi@drp-srcf-eb002 launchpad]$ cat slurm-496185.out
ana-4.0.46-py3        *  /cds/sw/ds/ana/conda1/inst/envs/ana-4.0.46-py3
/cds/sw/ds/ana/conda1/inst/envs/ana-4.0.46-py3/bin/mpirun
/cds/sw/ds/ana/conda1/inst/envs/ana-4.0.46-py3/bin/python
new config file: _200.yaml
/cds/sw/ds/ana/conda1/inst/envs/ana-4.0.38-py3/bin/python /cds/home/f/fpoitevi/btx1/scripts/main.py -c _200.yaml -t index
Traceback (most recent call last):
  File "/cds/home/f/fpoitevi/btx1/scripts/main.py", line 42, in <module>
    retval, status_message = main()
TypeError: cannot unpack non-iterable int object

Error: cannot create root path.
Error: Task failed.
```

Let me know if you think I can debug this - in which case please feel free to open the PR as a draft and we'll work things out from there.

**Comment by yilaili** [comment]
Hi Fred - you're right; I have fixed the typo in the most recent commit. Please let me know if the slurm job is able to run. One thing that I'm not sure is when running the command inside the slurm script, what's the relative path to the yaml file? This may also make the slurm job not runnable and I don't really know how to debug that.

**Comment by fredericpoitevin** [comment]
Great Yilai! Based on your fix I was able to find the few remaining instances where `config_file` needed to be changed from `config` and it runs now:
```bash
(myenv) [fpoitevi@drp-srcf-eb004 launchpad]$ submit_main.py -c ../yamls/t1calib25.yaml -t index -r 200 --index+tag clitest2
Config edited according to the inputs.
elog_submit.sh --config_file ../yamls/t1calib25-tmp.yaml --task index --run_number 200
Submitted batch job 498612
Job sent to queue
```
```bash
(myenv) [fpoitevi@drp-srcf-eb004 launchpad]$ cat slurm-498612.out
ana-4.0.46-py3        *  /cds/sw/ds/ana/conda1/inst/envs/ana-4.0.46-py3
/cds/sw/ds/ana/conda1/inst/envs/ana-4.0.46-py3/bin/mpirun
/cds/sw/ds/ana/conda1/inst/envs/ana-4.0.46-py3/bin/python
new config file: ../yamls/t1calib25-tmp_200.yaml
/cds/sw/ds/ana/conda1/inst/envs/ana-4.0.38-py3/bin/python /cds/home/f/fpoitevi/btx1/scripts/main.py -c ../yamls/t1calib25-tmp_200.yaml -t index
DEBUG:scripts.tasks:Generating indexing executable for run 200 of mfxc00120...
Submitted batch job 498613
INFO:scripts.tasks:Indexing launched!
Indexing executable written to /cds/home/f/fpoitevi/.btx//task_37c8152e-35e7-4287-afdb-e324216e9a06.sh
Task successfully executed
```

**Comment by fredericpoitevin** [comment]
I pushed it to your PR so I think it's safe to merge!

**Comment by yilaili** [comment]
Thanks!! Follow up question: where will the output of the running jobs be stored? Is there a parameter to specify this?

**Comment by fredericpoitevin** [comment]
Each task would have some kind of sub-directory under `config.setup.root_dir`. 
Maybe the `eLogInterface` helps a little bit see how it works? https://github.com/lcls-users/btx/blob/main/btx/interfaces/ielog.py

The relative path at this point is hard-coded but I'd like to revisit how we do this - for example, see #191.

**Comment by yilaili** [comment]
So, is this `root_dir` changeable for every different job launched through `elog_submit.sh`, or you'd prefer it to be the same for different jobs? Is it ok if I set `root_dir` as something like `./LCLS/job001` (like in RELION), so that all output files and folders generated from this slurm job will be stored in this directory?
