### ISSUE TITLE
make all tasks use `iScheduler`

### ISSUE THREAD

**Issue by apeck12** [lcls-users/btx#226]
The following tasks need to be changed:
- opt_geom
- find_peaks
- stream_analysis (done in PR #233)
- run_analysis (done in PR #239)
- visualize_sample (?)

**Comment by apeck12** [comment]
`stream_analysis` done in PR #233

**Comment by fredericpoitevin** [comment]
#330 took care of all tasks in `process_sfx` DAG. Closing.
