### ISSUE TITLE
Automated model building

### ISSUE THREAD

**Issue by fredericpoitevin** [lcls-users/btx#259]
We should look into what's on the market for automated model building and see what could easily be made available

**Comment by apeck12** [comment]
I think Phenix's Autosol is widely-used and may be the easiest to integrate: https://phenix-online.org/documentation/reference/autosol.html.

**Comment by fredericpoitevin** [comment]
Perfect! Let's plan on implementing that task and then figure out how it fits in terms of workflow (since we assume we only do MR for now). Thanks!
