### ISSUE TITLE
Shared file for IO from task results

### ISSUE THREAD

**Issue by gadorlhiac** [lcls-users/btx#267]
Should we include a single centralized file for storing output results/figure data from various tasks?

A potential option could be hdf5. Additional tasks/routines could be provided for extracting the data into txt/png files as needed.

**Comment by fredericpoitevin** [comment]
We discussed replacing the current directory of folders by a single hdf5 file that is handled by a single class.

**Comment by fredericpoitevin** [comment]
Will be handled by hdf5 approach.
