### ISSUE TITLE
Interactive visualization of processed streaming data.

### ISSUE THREAD

**Issue by john-winnicki** [lcls-users/btx#268]
We need a "dynamic" way to generate interactive plots - static interactive plots are too limiting, in particular in a streaming setting.

Requirements:
- [Holoviews](https://holoviews.org/user_guide/Live_Data.html#)
- [Bokeh Apps](https://holoviews.org/user_guide/Deploying_Bokeh_Apps.html) [+Bokeh App docs+](https://docs.bokeh.org/en/latest/docs/user_guide/server/app.html#ug-server-apps)
- [Bokeh servers](https://docs.bokeh.org/en/latest/docs/user_guide/server.html)
- [Running a server from Jupyter notebook?](https://holoviews.org/user_guide/Deploying_Bokeh_Apps.html#inlining-apps-in-the-notebook)
- [Working with streaming data](https://holoviews.org/user_guide/Streaming_Data.html)
- [Instantiating a server behind the eLog?](s3df.slac.stanford.edu)

Essentially, we'd have a `.h5` file being constantly updated as more data is being processed. Periodically or upon user input, the data would be pulled and displayed in an interactive fashion - possibly using light processing such as optimal datashading, clustering, etc. and generating images.

**Comment by fredericpoitevin** [comment]
We need a "dynamic" way to generate interactive plots - static interactive plots are too limiting, in particular in a streaming setting.

Requirements:
- [Holoviews](https://holoviews.org/user_guide/Live_Data.html#)
- [Bokeh Apps](https://holoviews.org/user_guide/Deploying_Bokeh_Apps.html)
- [Bokeh servers](https://docs.bokeh.org/en/latest/docs/user_guide/server.html)
- [Running a server from Jupyter notebook?](https://holoviews.org/user_guide/Deploying_Bokeh_Apps.html#inlining-apps-in-the-notebook)
- [Working with streaming data](https://holoviews.org/user_guide/Streaming_Data.html)
- [Instantiating a server behind the eLog?](s3df.slac.stanford.edu)

Essentially, we'd have a `.h5` file being constantly updated as more data is being processed. Periodically or upon user input, the data would be pulled and displayed in an interactive fashion - possibly using light processing such as optimal datashading, clustering, etc. and generating images.

**Comment by fredericpoitevin** [comment]
PiPCA and Frequent Directions have shown ways to do this.
