### ISSUE TITLE
Data loading on GPU

### ISSUE THREAD

**Issue by fredericpoitevin** [lcls-users/btx#274]
We expect data loading to be the main bottleneck for GPU code. While this needs to be quantified, let's dig into mitigation approaches.

# Loading from disk
- https://effectivemachinelearning.com/PyTorch/6._Building_efficient_custom_data_loaders
- https://gist.github.com/ZijiaLewisLu/eabdca955110833c0ce984d34eb7ff39
- https://github.com/vahidk/tfrecord

# CPU<->GPU transfer

**Comment by gadorlhiac** [comment]
I've run a very rudimentary test of CPU vs GPU processing speed and the time taken to transfer an object from CPU to GPU memory using Numba.

Using an array of 356x384 integers I tested a rough equivalent to the calibration procedure on ePix cameras. As far as I can tell this operation involves 4 operations:
1. Pedestal subtraction
2. Offset (gain-mode) dependent
3. Common mode correction
4. Gain mode correction

Boiling this down to the simplest per pixel operations, I tested the time it took to perform 3 additions and one multiplication for every position in the array. The three test cases were:
1. Pure numpy and allow it to handle broadcasting (CPU)
2. Allow numba to transfer numpy arrays to the GPU and then perform the calculations on GPU
3. Transfer the arrays to GPU in a separate step. Time only the GPU operations.


The results for the three cases are as follows:

![image](https://user-images.githubusercontent.com/18701604/220763912-9f2d7664-a719-4752-af9b-8d3165631168.png)

**Comment by fredericpoitevin** [comment]
https://onlinelibrary.wiley.com/doi/pdf/10.1107/S1600577520008140

**Comment by gadorlhiac** [comment]
https://journals.iucr.org/j/issues/2021/05/00/te5078/

https://indico.psi.ch/event/12738/contributions/38902/attachments/22756/40116/2022-09-21-NoBugs2022-short.pdf

**Comment by gadorlhiac** [comment]
https://www.nature.com/articles/s41467-020-17285-3#Sec37

**Comment by fredericpoitevin** [comment]
# [Smart sensors using artificial intelligence for on-detector electronics and ASICs](https://github.com/lcls-users/btx/files/10913368/2204.13223.pdf)
