### ISSUE TITLE
NERSC remote analysis

### ISSUE THREAD

**Issue by fredericpoitevin** [lcls-users/btx#3]
Write a short note on how to login to NERSC (using sshproxy so the connection lasts 24h), and using NoMachine.

**Comment by apeck12** [comment]
A section on the Wiki has been created here: https://github.com/lcls-users/sfx/wiki/Get-started#nersc-remote-analysis

**Comment by fredericpoitevin** [comment]
Obsolete, this'll go in `lcls-users`
