### ISSUE TITLE
`retrieve_pixel_index_map` not working for pnCCD detector

### ISSUE THREAD

**Issue by fredericpoitevin** [lcls-users/btx#309]
I was trying to assemble a pnCCD detector image using the tools in `ipsana`: https://github.com/lcls-users/btx/blob/983a6efb026d791645eb4dab352133fc17dea969/btx/interfaces/ipsana.py#L377

```python
from PSCalib.GeometryAccess import GeometryAccess
geom = GeometryAccess("/cds/data/psdm/amo/amo06516/calib/PNCCD::CalibV1/Camp.0:pnCCD.0/geometry/38-end.data")
```

But had to hack the shape to get it to work:
```python
temp_index = [np.asarray(t) for t in geom.get_pixel_coord_indexes()]
temp_index = np.array(temp_index).reshape((2,1,4,512,512))    # <== hack: initial shape: (2,1,2,2,512,512)
pixel_index_map = np.zeros((np.array(temp_index).shape[2:]) + (2,))
pixel_index_map[:,:,:,0] = temp_index[0][0]
pixel_index_map[:,:,:,1] = temp_index[1][0]
pixel_index_map = pixel_index_map.astype(np.int64)
```

**Comment by gadorlhiac** [comment]
This dimensionality problem should be resolved by #313. The PR covers the case of (dis)assembling images where `retrieve_pixel_index_map` returns a map where more than one dimension is used for iterating over panels/asics. Specifically it covers the cases where the map is of the form `(n_panels, fs_shape, ss_shape, ...)` and `(panel_idx1, panel_idx2, fs_shape, ss_shape, ...)`
