### ISSUE TITLE
`indexer` reporting does not run when called with `mpirun`

### ISSUE THREAD

**Issue by gadorlhiac** [lcls-users/btx#323]
# Overview
When running the `index` task, the second batch submission script, if using more than one core will look something like this:
```
#BATCH STUFF
indexamajig ...                                                 # <- Job executes fine
mpirun -n {ncores} python {btx_path}/processing/indexer.py ...  # <- Job does not execute
```
The second line is added to call the elog reporting features, so while processing occurs, no feedback is provided. Interestingly this problem does not occur under the following two scenarios:
- The second line is called without `mpirun`
- A minimal test example emulating the behaviour of `btx` is used (I.e. running through all the batch submission steps/levels)

### Running without `mpirun`
If the following portion of `btx.interfaces.ischeduler._find_python_path` are commented out, then the result is a batch script that is submitted with just python.
```
        for ppath in possible_paths:
            if os.path.exists(ppath):
                pythonpath = ppath
                # if self.ncores > 1:                                                                                                         # Line 55
                #     pythonpath = f"{os.path.split(ppath)[0]}/mpirun -n {self.ncores} {ppath}" # Line 56
```

With the corresponding batch script
```
#BATCH STUFF
indexamajig ....
python {btx_path}/processing/indexer.py ...
```

This runs without a problem.

### Toy example
To emulate the multi-step submission process I created a toy example that did the same thing, where the last step was the submission of an actual secondary batch script produced by `btx`. This requires submitting the file `/sdf/data/lcls/ds/mfx/mfxp23120/scratch/btx_dorlhiac/launchpad/test_batch.sh` which in turn submits `test.py` in the same directory, which in turn submits the batch script `task_....sh` in the `.btx` directory of my home folder (where the temp files are written). Due to the possibility of permissions problems when others try to submit/run these files, I reproduce the contents of the files below.

**This toy example ran without problem**, even though it invoked `mpirun` and not just python directly. Some of the log file directories were changed and certain dependencies weren't written in order to simplify the submission.

#### `test_batch.sh`
```
#!/bin/bash
#SBATCH -p milano
#SBATCH --job-name=multilevel
#SBATCH --output=../ml.out
#SBATCH --error=../ml.err
#SBATCH --ntasks=1
#SBATCH --time=1:00:00
#SBATCH --exclusive

python ./test.py
```

#### `test.py`
```
import os
os.system('sbatch ~/.btx/task_07d30d20-1e3d-4f03-871a-919ee5277933.sh')
```

#### `task_07d30d20-1e3d-4f03-871a-919ee5277933.sh`
```
#!/bin/bash
#SBATCH -p milano
#SBATCH --job-name=idx_r0131
#SBATCH --output=./../logs.out
#SBATCH --error=./../logs.err
#SBATCH --ntasks=64
#SBATCH --time=2:00:00
#SBATCH --exclusive

#SBATCH -A lcls

export PATH=/sdf/group/lcls/ds/tools/crystfel/0.10.2/bin:$PATH
export PATH=/sdf/group/lcls/ds/tools/:$PATH

export SIT_PSDM_DATA=/sdf/data/lcls/ds/

/sdf/group/lcls/ds/ana/sw/conda1/inst/envs/ana-4.0.47-py3/bin/mpirun -np 64 /sdf/group/lcls/ds/ana/sw/conda1/inst/envs/ana-4.0.47-py3/bin/python /sdf/home/d/dorlhiac/btx/btx/processing/indexer.py -e mfxp23120 -r 131 -d epix10k2M --taskdir /sdf/data/lcls/ds/mfx/mfxp23120/scratch/btx_dorlhiac/index --report --tag lyso
```

**Comment by gadorlhiac** [comment]
Upon further thought, this may be related to user error/unhandled errors.

The second example runs without the call to `indexamajig` which may be because after the first call to `indexamajig`, a `stream` file is created. If that file is present `indexamajig` will fail if called again, because it will refuse to overwrite the stream file. This may cause the job to finish without running the second line.

When testing I was running the job many times, and may have remembered to delete the `stream` file between some attempts and not others.

**Comment by fredericpoitevin** [comment]
Note - the following works:

```bash
(base) [fpoitevi@sdfiana001 launchpad]$ cat test1.sh
#!/bin/bash
#SBATCH -p milano
#SBATCH --job-name=multilevel
#SBATCH --output=./ml.out
#SBATCH --error=./ml.err
#SBATCH --ntasks=1
#SBATCH --time=1:00:00
#SBATCH --exclusive
#SBATCH -A lcls

python ./test1.py
```

```bash
(base) [fpoitevi@sdfiana001 launchpad]$ cat test1.py 
import os
os.system('sbatch test2.sh')
```

```bash
(base) [fpoitevi@sdfiana001 launchpad]$ cat test2.sh
#!/bin/bash
#SBATCH -p milano
#SBATCH --job-name=ml2
#SBATCH --output=./ml2.out
#SBATCH --error=./ml2.err
#SBATCH --ntasks=64
#SBATCH --time=2:00:00
#SBATCH --exclusive

#SBATCH -A lcls

export PATH=/sdf/group/lcls/ds/tools/crystfel/0.10.2/bin:$PATH
export PATH=/sdf/group/lcls/ds/tools/:$PATH

export SIT_PSDM_DATA=/sdf/data/lcls/ds/

/sdf/group/lcls/ds/ana/sw/conda1/inst/envs/ana-4.0.47-py3/bin/mpirun -n 64 python test2.py
```

```bash
(base) [fpoitevi@sdfiana001 launchpad]$ cat test2.py
from mpi4py import MPI

def main():
    print("testing testing...")
    comm = MPI.COMM_WORLD
    name=MPI.Get_processor_name()
    print(f"name: {name}, my rank is {comm.rank}")

if __name__ == '__main__':
    main()
```

**Comment by fredericpoitevin** [comment]
Changing the `command` in `Indexer` to a similar simple test fails. Here is the slurm script written and submitted by iScheduler:
```bash
(base) [fpoitevi@sdfiana001 launchpad]$ cat /sdf/home/f/fpoitevi/.btx//task_0e02d8b8-1bfe-4bff-81a7-71117e00eb1f.sh
#!/bin/bash
#SBATCH -p milano
#SBATCH --job-name=idx_r0131
#SBATCH --output=./idx_r0131.out
#SBATCH --error=./idx_r0131.err
#SBATCH --ntasks=64
#SBATCH --time=2:00:00
#SBATCH --exclusive

#SBATCH -A lcls

export PATH=/sdf/group/lcls/ds/tools/crystfel/0.10.2/bin:$PATH
export PATH=/sdf/group/lcls/ds/tools/:$PATH

export SIT_PSDM_DATA=/sdf/data/lcls/ds/

/sdf/group/lcls/ds/ana/sw/conda1/inst/envs/ana-4.0.47-py3/bin/mpirun -n 64 /sdf/group/lcls/ds/ana/sw/conda1/inst/envs/ana-4.0.47-py3/bin/python /sdf/data/lcls/ds/mfx/mfxp23120/scratch/fpoitevi/launchpad/test2.py
```
```bash
(base) [fpoitevi@sdfiana001 launchpad]$ sacct -j 18567556
JobID           JobName  Partition    Account  AllocCPUS      State ExitCode 
------------ ---------- ---------- ---------- ---------- ---------- -------- 
18567556      idx_r0131     milano       lcls        125     FAILED      1:0 
18567556.ba+      batch                  lcls        125     FAILED      1:0 
18567556.ex+     extern                  lcls        125  COMPLETED      0:0 
```

**Comment by gadorlhiac** [comment]
It seems that this problem can be resolved through conditional import of `mpi4py` in both `main` and `indexer`. This can be accomplished by:
- Passing an additional parameter to `main` via a command-line argument used in `elog_submit` (`-n $CORES`)
- Passing an additional parameter to `indexer` during object initialization (`mpi_init`).

(Refer to linked PR #325 for the relevant changes)

For the multi-step jobs MPI should not be initialized during the first job submission, but it is needed for the second round, so, while ungainly, this method might be able to help.
