### ISSUE TITLE
Automatic DAG definition from YAML file.

### ISSUE THREAD

**Issue by fredericpoitevin** [lcls-users/btx#35]
> That sounds good! As an alternative, I wasn't sure if we were going to have another entry in the yaml that defined which of the tasks would be run and in which order.

@apeck12 that's a nice feature to have in the future! This would require something that interprets the YAML and writes the DAG definition file, something like: 
```python
write_dag_from_yaml(config, dag_file)
```
where `config` would be https://github.com/lcls-users/btx/blob/main/tutorial/det_distance.yaml and `dag_file` would be https://github.com/lcls-users/btx/blob/main/dags/det_distance.py

Definitely something we should implement!

_Originally posted by @fredericpoitevin in https://github.com/lcls-users/btx/issues/34#issuecomment-1098418376_

**Comment by tsgit** [comment]
for reference:   dags from yaml  
https://github.com/ajbosco/dag-factory
https://towardsdatascience.com/abstracting-data-loading-with-airflow-dag-factories-12b6689f0aaa
https://donagh.io/2019/04/17/configuring-airflow-dags-with-yaml.html
