### ISSUE TITLE
`geoptimizer` task

### ISSUE THREAD

**Issue by fredericpoitevin** [lcls-users/btx#89]
Figure out and document how to run on any LCLS detector.

For example, for epix10k2M: `/reg/g/cfel/crystfel/crystfel-0.8.0/bin/geoptimiser -c asics -q quadrants -m 8 -i $INPUT -g P21419-opt.geom -o p185_v1.geom --no-cspad`

**Comment by apeck12** [comment]
https://www.desy.de/~twhite/crystfel/manual-geoptimiser.html

**Comment by apeck12** [comment]
For CrystFEL version 9: `$ source /reg/g/cfel/crystfel/crystfel-0.9.1/setup-sh`. (See https://www.desy.de/~twhite/crystfel/facilities.html for more details).

We may also need a function in metrology.py that converts the header from CrystFEL 10 to 9 format by commenting out the `peak_list` and `peak_list_type` lines. This can be done by adding a semicolon to the beginning of the line.

**Comment by valmar** [comment]
There is a lot of heuristic involved in running the geoptimiser, and even more in interpreting its results. For example, errors are capped at 1pixel. Any error above 1px will show up in the error plots as a 1pix error, etc. I would reach out to Oleksandr Yefanov at DESY, and maybe ask him to hold some training. Knowing him, he will be happy to. Contact: oleksandr.yefanov@desy.de
