### ISSUE TITLE
Sort images by event code 

### ISSUE THREAD

**Issue by apeck12** [lcls-users/btx#93]
Figure out (1) the relevant event code and (2) how to sort images during peak finding -- changes probably need to be made both to the `PsanaInterface` and `PeakFinder` classes.

**Comment by fredericpoitevin** [comment]
The event code logic was captured here: https://github.com/apeck12/sfx_utils/blob/TTscripts/sfx_utils/laser_state.py

Implementing it in `psana_interface` now.

**Comment by fredericpoitevin** [comment]
Closed by #106
