### ISSUE TITLE
Expanding on variable nomenclature and docstrings in ConcentricCircles classes

### ISSUE THREAD

**Issue by apeck12** [lcls-users/btx#96]
Instead of `num`, perhaps we could use something more explicit, like `num_circle_points` or `num_quadrature`?

_Originally posted by @fredericpoitevin in https://github.com/lcls-users/btx/pull/90#discussion_r870877643_

@carbonscott, what is the definition of the residual during fitting?

**Comment by carbonscott** [comment]
@apeck12 @fredericpoitevin Agree on giving it a better variable name, maybe `num_circle_points` or `num_points_from_circle`?  I am not familiar with the word `quadrature`, so maybe it's better to keep using simple English words.  

The residual here is defined by the difference between a selected pixel value and the max pixel value of the whole image.  It's implemented [here](https://github.com/lcls-users/btx/blob/c17fbda97e28ae93e0d6e0c178c379bd1114c4b2/btx/misc/radial.py#L231).  This way, minimizing the residual (departure from the max) using least square is equivalent to finding the overall brightest pixels that form concentric circles.   Let me know if it makes sense.

**Comment by fredericpoitevin** [comment]
Sounds good for the variable name @carbonscott - I meant it as ["Squaring the circle"](https://en.wikipedia.org/wiki/Squaring_the_circle)

For the residual definition: thanks, I think that's what I gathered from the code, maybe just add what you just wrote above to the docstring?

**Comment by carbonscott** [comment]
@fredericpoitevin sounds good.  Maybe it can be phrased more concisely.  What I said was a bit wordy.
